### ISSUE TITLE
UpgradeApplication: Update required.

### ISSUE THREAD

**Issue by BeeeQueue** [seiya-dev/hidive-downloader-nx#12]
**Main info:**
HIDIVE has updated their API in some way so the current auth details don't work. Do you know how to get the new ones? 

BeeeQueue/yuna#123

Script version: any
Show ID: any
Episode ID: any

**Comment by seiya-git** [comment]
Thanks, I will try to fix it as soon as possible.

**Comment by seiya-git** [comment]
they moved key to `libnative-lib.so` so I can't fix it, need someone who can reverse engineer this lib

**Comment by seiya-git** [comment]
https://github.com/seiya-dev/hidive-downloader-nx/releases/tag/1.9.0
fixed

**Comment by BeeeQueue** [comment]
Thanks ❤️
