### ISSUE TITLE
always get error code 81 no matter what

### ISSUE THREAD

**Issue by storm134** [seiya-dev/hidive-downloader-nx#13]
** Main info: **
just upgrade to 1.8, windows 10 64
Script version: 
Show ID: 
Episode ID: 

** Additional Info: **
[ERROR] Code 81 (UpgradeApplication): Update required. Visit Google Play for current HIDIVE app. Please try again. If the problem persists, please contact help@hidive.com.

**Comment by XxUnkn0wnxX** [comment]
this issue has already been posted #12 
Dev is well aware, may take a while to fix though...
