### ISSUE TITLE
Error 404 on every show

### ISSUE THREAD

**Issue by anor4k** [seiya-dev/hidive-downloader-nx#16]
** Main info: **

Script version: 1.9.3
Show ID: 947
Episode ID: s01e001

** Additional Info: **
I'm getting error 404 regardless of what I try to download. New shows, old shows, batch, japanese or english dubs. I'm not using a proxy, and I can watch the shows normally through official apps and web browser.

Here's what I get:
```
$ node hidive -s 947 -e s01e001 -q 1080p --dub jpn

=== HIDIVE Downloader NX 1.9.3 ===

[#947] The Demon Girl Next Door [Season 1 | 12 Episodes | TV-14]
[s01e001] Yuko Awakens!! For Family Reasons You're Now a Demon Girl (selected)
 - Audio: Japanese
 - Subtitles: English
[s01e002] Just How Sporty Are You?! Everything is Fluctuating
 - Audio: Japanese
 - Subtitles: English
[s01e003] Nightmare or Forebear?! The Doorstop of Darkness Descends
 - Audio: Japanese
 - Subtitles: English
[s01e004] Coming Soon
 - Audio: 
 - Subtitles: 
[s01e005] Coming Soon
 - Audio: 
 - Subtitles: 
[s01e006] Coming Soon
 - Audio: 
 - Subtitles: 
[s01e007] Coming Soon
 - Audio: 
 - Subtitles: 
[s01e008] Coming Soon
 - Audio: 
 - Subtitles: 
[s01e009] Coming Soon
 - Audio: 
 - Subtitles: 
[s01e010] Coming Soon
 - Audio: 
 - Subtitles: 
[s01e011] Coming Soon
 - Audio: 
 - Subtitles: 
[s01e012] Coming Soon
 - Audio: 
 - Subtitles: 

[INFO] The Demon Girl Next Door - 01
[INFO] Available dubs and subtitles:
	Videos: Japanese, Broadcast, TV-14
	Subs  : English Subs
[INFO] Selected dub: Japanese
[INFO] Selected release: Broadcast

[ERROR] HTTPError 404: Not Found
```

**Comment by anor4k** [comment]
anor4k#5650

**Comment by storm134** [comment]
same issue with me as well always get error 404.

**Comment by storm134** [comment]
=== HIDIVE Downloader NX 1.9.3 ===

[#847] Cutie Honey Universe [Season 1 | 12 Episodes | TV-MA]
[s01e001] Everything About You is Perfect (selected)
 - Audio: Japanese, English
 - Subtitles: English, Portuguese, Spanish LatAm
[s01e002] The True Joy of Having Met You
 - Audio: Japanese, English
 - Subtitles: English, Spanish LatAm, Portuguese
[s01e003] I Am Made For You
 - Audio: Japanese, English
 - Subtitles: English, Portuguese, Spanish LatAm
[s01e004] Pure Beauty
 - Audio: Japanese, English
 - Subtitles: English, Spanish LatAm, Portuguese
[s01e005] Till Death Do Us Part
 - Audio: Japanese
 - Subtitles: English, Portuguese, Spanish LatAm
[s01e006] May Fortune Befall You
 - Audio: Japanese
 - Subtitles: English, Spanish LatAm, Portuguese
[s01e007] Devotion to You Alone
 - Audio: Japanese
 - Subtitles: English, Portuguese, Spanish LatAm
[s01e008] Vows of Love
 - Audio: Japanese
 - Subtitles: English, Spanish LatAm, Portuguese
[s01e009] The Whole World is Just You and Me
 - Audio: Japanese
 - Subtitles: English, Portuguese, Spanish LatAm
[s01e010] Thank You for Your Compassion and Encouragement
 - Audio: Japanese
 - Subtitles: Spanish LatAm, Portuguese, English
[s01e011] You Will Be Mine
 - Audio: Japanese
 - Subtitles: English, Portuguese, Spanish LatAm
[s01e012] You Will Return with Hope
 - Audio: Japanese
 - Subtitles: English, Portuguese, Spanish LatAm

[INFO] Cutie Honey Universe - 01
[INFO] Available dubs and subtitles:
        Videos: Japanese, Broadcast, TV-14
                Japanese, Home Video, TV-MA
                English, Home Video, TV-MA
        Subs  : English Subs
                Portuguese Subs
                Spanish LatAm Subs
                English Caps
[INFO] Selected dub: English
[INFO] Selected release: Home Video

[ERROR] HTTPError 404: Not Found

i am in canada, no proxy, i have fiber op, using windows 10/64 no vpn. also able to with with browser or app.

**Comment by CHJ85** [comment]
I thought I was the only one having this problem.
But I thought it was because I am using Linux, and Youtube-dl works, so I didn't report it.

**Comment by anor4k** [comment]
I am on macOS, so we have three OSes that don’t work. Also, I’m located in Brazil, if it makes a difference. Haven’t tested youtube-dl.

**Comment by anor4k** [comment]
Did a bit of debugging with what little knowledge I have, and the request that returns 404 is `get data(videoUrl)` on line 376. On my example, videoURL is `https://api.hidive.com/manifest/master/51b5cc6798e6f2e688d2a356d198fd6126b649a7/MMZ_s01e001_tv_br_or_ja_xx_HLS_16x9_01_v.m3u8`
I don't know what else to do now to discover why is it throwing the error (bad URL? headers? I have no idea)

**Comment by basuritashka** [comment]
I got the same error.

**Comment by XxUnkn0wnxX** [comment]
yep getting same issue:

`[INFO] Why the Hell are You Here, Teacher!? - 01
[INFO] Available dubs and subtitles:
	Videos: English, Broadcast, TV-MA
		Japanese, Broadcast, TV-MA
	Subs  : English Caps
		English Subs
		Portuguese Subs
		Spanish LatAm Subs
[INFO] Selected dub: English
[INFO] Selected release: Broadcast

[ERROR] HTTPError 404: Not Found`

but only on some shows...

**Comment by seiya-git** [comment]
Relogin didn't help?

**Comment by XxUnkn0wnxX** [comment]
nope.. doesnt help i allways flush cookes with every new update anyway...

**Comment by seiya-git** [comment]
Ok, I will try fix it.

**Comment by seiya-git** [comment]
fixed in latest release
