### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by flashpc** [seiya-dev/hidive-downloader-nx#17]
** Main info: **

Script version: 1.10
Show ID: 940
Episode ID: s02e000

** Additional Info: **

Used the old code before albeit a while ago and updated and this is the error that comes up

[INFO] Is It Wrong to Try to Pick Up Girls in a Dungeon? II S2 - 00
[INFO] Available dubs and subtitles:
        Videos: English, Broadcast, TV-14
                Japanese, Broadcast, TV-14
        Subs  : English Caps
                English Subs
                Spanish LatAm Subs
                Portuguese Subs
                Arabic Subs
[INFO] Selected dub: English
[INFO] Selected release: Broadcast
(node:9200) UnhandledPromiseRejectionWarning: ReferenceError: URLSearchParams is
 not defined
    at reqData (D:\HiDive Downloader\hidive.js:686:48)
    at getData (D:\HiDive Downloader\hidive.js:627:18)
    at downloadMedia (D:\HiDive Downloader\hidive.js:386:35)
    at getShow (D:\HiDive Downloader\hidive.js:354:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:9200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 4)
(node:9200) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

Any help?

**Comment by seiya-git** [comment]
Update nodejs to 10+
