### ISSUE TITLE
All the lines in subtitles say "undefined"?

### ISSUE THREAD

**Issue by Truanifan** [seiya-dev/hidive-downloader-nx#2]
** Main info: In the forums you mentioned making an issue post here so I thought I'd do that this time.
I think I spoke too soon. It looked like everything was working at first glance, but when I finally got the time to watch something every line in the subs/caps says "undefined." I noticed it in Godzilla 1984 and tested it on some other random titles including Log Horizon. Sorry...😓 

This is what I used:
`hidive -s 593 -e 1984121501 -q 1080p --dub jpn --mks`
I tested the same code on version 1.1.0 and the subs worked...**

Script version: 1.2.0
Show ID: 593
Episode ID: 1984121501

** Additional Info: **

**Comment by seiya-git** [comment]
Fixed with new version @[1.2.1](../releases/tag/1.2.1)
