### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by storm134** [seiya-dev/hidive-downloader-nx#8]
** Main info: **
Not sure if this happen before and i just did not notice it. but get error 500 after download. episode still seems fine as far as i can tell.

Script version: 1.7.1
Show ID: any
Episode ID: any

** Additional Info: **
[INFO] Video downloaded!

[ERROR] 500
{
        "statusCode": 500,
        "body": "\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>HIDIVE - HTTP 500</title>\r\n    <meta charset=\"utf-8\" />\r\n    <link href=\"/Content/bootstrap.min.css\" rel=\"stylesheet\" />\r\n    <script src=\"/scripts/bootstrap.min.js\"></script>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <div class=\"row\">\r\n            <div class=\"col-xs-12\"><img src=\"/500.jpg\" class=\"img-responsive\" /></div>\r\n        </div>\r\n        <div  class=\"row\">\r\n            <div class=\"col-xs-12 text-center h1 text-uppercase\">\r\n                <p>\r\n                    Uuuhhhhhh.....\r\n                </p>\r\n                <p>\r\n                    Something isn’t quite right,<br />\r\n                    looks like a slight malfunction.\r\n                </p>\r\n                <p>\r\n                    LENNY is grabbing the<br />\r\n                    toolbox as we speak.\r\n                </p>\r\n                <p>\r\n                    SCREWDRIVER: &#x2714;<br />\r\n                    DUCT TAPE: &#x2714;<br />\r\n                    WD-40: &#x2714;<br />\r\n                    PACK OF MOONPIES: &#x2718;\r\n                </p>\r\n                <p>\r\n                    HURRY LENNY!<br />\r\n                    seriously?! MOON PIES?<br />\r\n                    JEEEEZ.\r\n                </p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</body>\r\n</html>\r\n",
        "headers": {
                "date": "Thu, 07 Mar 2019 14:30:41 GMT",
                "content-type": "text/html; charset=utf-8",
                "content-length": "1323",
                "connection": "close",
                "cache-control": "private",
                "server": "Microsoft-IIS/8.5",
                "x-aspnet-version": "4.0.30319",
                "x-powered-by": "ASP.NET",
                "access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, Range",
                "access-control-allow-methods": "GET, POST, PUT, DELETE, OPTIONS"
        },
        "request": {
                "uri": {
                        "protocol": "https:",
                        "slashes": true,
                        "auth": null,
                        "host": "api.hidive.com",
                        "port": 443,
                        "hostname": "api.hidive.com",
                        "hash": null,
                        "search": "?id=FVB_s01e003_tv_br_or_ja_en_v02.css",
                        "query": "id=FVB_s01e003_tv_br_or_ja_en_v02.css",
                        "pathname": "/caption/css/",
                        "path": "/caption/css/?id=FVB_s01e003_tv_br_or_ja_en_v02.css",
                        "href": "https://api.hidive.com/caption/css/?id=FVB_s01e003_tv_br_or_ja_en_v02.css"
                },
                "method": "GET",
                "headers": {
                        "X-ApplicationId": "24i-Android",
                        "X-DeviceId": "dd8bcbc5-7dcd-42b2-9370-380b8a06abc4",
                        "X-VisitId": "0ecd6cf2-486c-4546-aa2c-be4c6b842358",
                        "X-UserId": 75132,
                        "X-ProfileId": 78957,
                        "X-Nonce": "7ed814433ce9b4bc6a23fccfd2e5955e618640fa6df65ec5e3d6707760d98a7a",
                        "X-Signature": "8deee549696fee2b4e6ae4f791cee80e112cc101dbe682ba82c898b6dfd64d5e",
                        "User-Agent": "smartexoplayer/1.6.0.R (Linux;Android 6.0) ExoPlayerLib/2.6.0",
                        "Cookie": ".AspNet.ApplicationCookie=Twv_c1RNtUfwqk2aS1ldFaCSn-AgsZQq1pmm31PbJ8tJSLhz0jpjZ3FaaxJClf3cAu6D-KrTiGJhNhg7DlMF7svdC5J5WU8wRO5QUtoD5ITu882vX0ZJprdmZcgybrqNTsaleaUy2iI_Tja-x4xiSKeyQwnVFXGnw6x2yH877TAlsnNZSJ2BKEVtifvJhEbuFcOc1M4vu7RwJLpSED-498Ganzy3oqEkC5HXCGm4U4HAq3CVHRnQftexOFGvkUq2XZNvdlQ7C4cb-u2oroNTCllTzjs1RIOlHtS-qv-ab3lMDhnWIrTXHfHKqQe2TLA72PQIFyh2yRvjwcLJB1nqfhwTPh-pH0hj0d9UdNZve7lBGC-AYi6yqOEogWFnbdtxhYHdUuAeBFsprtOQM3iGyX4WuJf2FLOSnGEzo-4mLeyJe_FdkMQYyYZUJVtMw3ZGxsQMfA; ASP.NET_SessionId=ddwippctryxqgpneesoztrbi; Visitor=120bd9ee994e4f8fbc901338b65dd494; VisitId=67381e2618b544a495d8478d54889cde"
                }
        }
}
[ERROR] 500
{
        "statusCode": 500,
        "body": "\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>HIDIVE - HTTP 500</title>\r\n    <meta charset=\"utf-8\" />\r\n    <link href=\"/Content/bootstrap.min.css\" rel=\"stylesheet\" />\r\n    <script src=\"/scripts/bootstrap.min.js\"></script>\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <div class=\"row\">\r\n            <div class=\"col-xs-12\"><img src=\"/500.jpg\" class=\"img-responsive\" /></div>\r\n        </div>\r\n        <div  class=\"row\">\r\n            <div class=\"col-xs-12 text-center h1 text-uppercase\">\r\n                <p>\r\n                    Uuuhhhhhh.....\r\n                </p>\r\n                <p>\r\n                    Something isn’t quite right,<br />\r\n                    looks like a slight malfunction.\r\n                </p>\r\n                <p>\r\n                    LENNY is grabbing the<br />\r\n                    toolbox as we speak.\r\n                </p>\r\n                <p>\r\n                    SCREWDRIVER: &#x2714;<br />\r\n                    DUCT TAPE: &#x2714;<br />\r\n                    WD-40: &#x2714;<br />\r\n                    PACK OF MOONPIES: &#x2718;\r\n                </p>\r\n                <p>\r\n                    HURRY LENNY!<br />\r\n                    seriously?! MOON PIES?<br />\r\n                    JEEEEZ.\r\n                </p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</body>\r\n</html>\r\n",
        "headers": {
                "date": "Thu, 07 Mar 2019 14:30:42 GMT",
                "content-type": "text/html; charset=utf-8",
                "content-length": "1323",
                "connection": "close",
                "cache-control": "private",
                "server": "Microsoft-IIS/8.5",
                "x-aspnet-version": "4.0.30319",
                "x-powered-by": "ASP.NET",
                "access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, Range",
                "access-control-allow-methods": "GET, POST, PUT, DELETE, OPTIONS"
        },
        "request": {
                "uri": {
                        "protocol": "https:",
                        "slashes": true,
                        "auth": null,
                        "host": "api.hidive.com",
                        "port": 443,
                        "hostname": "api.hidive.com",
                        "hash": null,
                        "search": "?id=FVB_s01e003_tv_hv_or_en_en_v00.css",
                        "query": "id=FVB_s01e003_tv_hv_or_en_en_v00.css",
                        "pathname": "/caption/css/",
                        "path": "/caption/css/?id=FVB_s01e003_tv_hv_or_en_en_v00.css",
                        "href": "https://api.hidive.com/caption/css/?id=FVB_s01e003_tv_hv_or_en_en_v00.css"
                },
                "method": "GET",
                "headers": {
                        "X-ApplicationId": "24i-Android",
                        "X-DeviceId": "dd8bcbc5-7dcd-42b2-9370-380b8a06abc4",
                        "X-VisitId": "0ecd6cf2-486c-4546-aa2c-be4c6b842358",
                        "X-UserId": 75132,
                        "X-ProfileId": 78957,
                        "X-Nonce": "7ed814433ce9b4bc6a23fccfd2e5955e618640fa6df65ec5e3d6707760d98a7a",
                        "X-Signature": "8deee549696fee2b4e6ae4f791cee80e112cc101dbe682ba82c898b6dfd64d5e",
                        "User-Agent": "smartexoplayer/1.6.0.R (Linux;Android 6.0) ExoPlayerLib/2.6.0",
                        "Cookie": ".AspNet.ApplicationCookie=Twv_c1RNtUfwqk2aS1ldFaCSn-AgsZQq1pmm31PbJ8tJSLhz0jpjZ3FaaxJClf3cAu6D-KrTiGJhNhg7DlMF7svdC5J5WU8wRO5QUtoD5ITu882vX0ZJprdmZcgybrqNTsaleaUy2iI_Tja-x4xiSKeyQwnVFXGnw6x2yH877TAlsnNZSJ2BKEVtifvJhEbuFcOc1M4vu7RwJLpSED-498Ganzy3oqEkC5HXCGm4U4HAq3CVHRnQftexOFGvkUq2XZNvdlQ7C4cb-u2oroNTCllTzjs1RIOlHtS-qv-ab3lMDhnWIrTXHfHKqQe2TLA72PQIFyh2yRvjwcLJB1nqfhwTPh-pH0hj0d9UdNZve7lBGC-AYi6yqOEogWFnbdtxhYHdUuAeBFsprtOQM3iGyX4WuJf2FLOSnGEzo-4mLeyJe_FdkMQYyYZUJVtMw3ZGxsQMfA; ASP.NET_SessionId=ddwippctryxqgpneesoztrbi; Visitor=120bd9ee994e4f8fbc901338b65dd494; VisitId=67381e2618b544a495d8478d54889cde"
                }
        }
}

> "mkvmerge" -o "[HIDIVE] My Girlfriend is Shobitch - 03 [720p].mkv" --disable-track-statistics-tags --engage no_variable_data --track-name "1:[HIDIVE]" --language "0:eng" --video-tracks 1 --audio-tracks 0 --no-subtitles --no-attachments "[HIDIVE] My Girlfriend is Shobitch - 03 [720p].ts"
mkvmerge v30.1.0 ('Forever And More') 64-bit
'[HIDIVE] My Girlfriend is Shobitch - 03 [720p].ts': Using the demultiplexer for the format 'MPEG transport stream'.
'[HIDIVE] My Girlfriend is Shobitch - 03 [720p].ts' track 0: Using the output module for the format 'AAC'.
'[HIDIVE] My Girlfriend is Shobitch - 03 [720p].ts' track 1: Using the output module for the format 'AVC/h.264 (unframed)'.
The file '[HIDIVE] My Girlfriend is Shobitch - 03 [720p].mkv' has been opened for writing.
'[HIDIVE] My Girlfriend is Shobitch - 03 [720p].ts' track 1: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1280/720.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 2 seconds.

[INFO] Done!

**Comment by flashpc** [comment]
same error, video downloads but no subtitles

**Comment by XxUnkn0wnxX** [comment]
yep still having same issue as posted here #9 seems he doesnt have any issues on his end & cannot re-produce it he wont fix it..

**Comment by flashpc** [comment]
@XxUnkn0wnxX what cookie info?

The problem seems to be between lines 495-501 I am a noob at this but that is where the URL is pulled from for the subtitles, I managed to build an ass file using the vtt2ass.bat file and download the vtt and css files using dev mode, so I know that part works although I had to adjust the timings in the ass file by 120 frames.

Once the maintence there end has completed will have a look

**Comment by XxUnkn0wnxX** [comment]
> @XxUnkn0wnxX what cookie info?
> 
> The problem seems to be between lines 495-501 I am a noob at this but that is where the URL is pulled from for the subtitles,
> 
> I got it to work by changing one line
> 
> change line 496 from
> 
> ```
> const prefix = 'https://api.hidive.com/caption';
> ```
> to
> 
> ```
> const prefix = 'https://www.hidive.com/caption';
> ```
> Not sure why but it works

thx I'll try it out.. I knew something had changes must of been URL then..

as for the cookie info ```"Cookie": ".AspNet.ApplicationCookie=``` delete that part as any one can use this information to log into your personal hidive account...

**Comment by seiya-git** [comment]
@XxUnkn0wnxX, actually I'm girl
@flashpc, this domains should do same behavior for subs, seems to me hidive broken something
i post fix after couple tests
