### ISSUE TITLE
Subtitles failing to download error 500

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [seiya-dev/hidive-downloader-nx#9]
** Main info: **

Script version: 1.7.1
Show ID: 915
Episode ID: s01e009

** Additional Info: **

log: https://gist.github.com/XxUnkn0wnxX/726b0a16ce801d9c69f2a2dd17d84483

seems to fail with previous episodes as well.

**Comment by seiya-git** [comment]
You'd better remove this gist because it's contains your account cookie.
It's works for me, so it was hidive server-side bug

**Comment by XxUnkn0wnxX** [comment]
i've hidden the cookie information.

i keep getting [ERROR] 500
{
	"statusCode": 500,

no matter what i do.
i try VPN
i try different account
i fresh reinstall the downloader

& subs still fail to download

my command is: node hidive -s 915 -q 1080p --mks -e s01e009 --dub jpn
